#!/bin/bash
#SBATCH --job-name=timescript
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4

srun /home/gresens/03-PDE/timescript >> /home/gresens/03-PDE/timescript.out &
wait
echo fertig > /home/gresens/03-PDE/job_script.out
